### PR TITLE
Beta 16 upgrade

### PR DESCRIPTION
**Pull request by luceos**
- [x] drops unified index
- [ ] introduces improved sidebar count/attention
- [ ] simplifies code (again)
- [ ] signed off by @imorland 
- [ ] signed off by @luceos

### CODE REVIEW

**Comment by imorland** [comment]
Although incomplete, I'm merging this branch now, so that `1.0` updates can be built on top of the wip progress here.

**Comment by Ornanovitch** [comment]
Seems to be a hard job, bravo!

Is it safe for beta 16?

**Comment by imorland** [comment]
> 
> 
> Seems to be a hard job, bravo!
> 
> Is it safe for beta 16?

Unfortunately no, there is no official support for this extension on beta 16

**Comment by Ornanovitch** [comment]
Got it, no problem, thanks for all you have done on this :)

**Pull request merged**
