### PR TITLE
Fix composer remaining open (minimised) when creating PD from user card

### LINKED ISSUE #120: Creating a new PD from the hover user card does not close the composer
Steps to reproduce:
- Hover over a user in a discussion use the `userControls` dropdown, select 'send X a message'
image
- Compose a private message
image
- Post the message
image

Note the composer is still in a `loading` state, and has not been closed. The private discussion is created, and we are redirected to it. No errors in `console`

Also note that manually closing the composer results in:
image

Additionally, creating a private message from the `userControls` on the `UserPage` uses the same code, but does not result in this behaviour.

This is defined here: https://github.com/FriendsOfFlarum/byobu/blob/9dec307ea855f62be48a4888a18ccbd3b9100014/js/src/forum/addDiscussPrivatelyControl.js#L21

### PR DESCRIPTION
**Pull request by davwheat**
Fixes #120 

This is a super simple change which seems to fix the issue.

Moving the composer hide until after we've navigated to the new discussion makes the composer hide correctly.

Possibly some super weird and barely reproducible upstream bug?

ezgif com-video-to-gif

### CODE REVIEW

**Comment by imorland** [comment]
So simple it's almost embarrasing, thank you for this @davwheat

**Comment by davwheat** [comment]
@imorland it still doesn't make sense to me though... Surely this should break in both instances of creating a PD?

**Comment by imorland** [comment]
Checking this out now! 🕺

**Comment by imorland** [comment]
You're a 🌟 Thank you so much for this, I will merge now!

**Pull request merged**
