### PR TITLE
Improve UX

### PR DESCRIPTION
**Pull request by imorland**
- Add 'Private Discussions' link to session dropdown
- Add sort option to `PrivateDiscussionUserPage`
- Add control to start a private discussion from the userpage
- Removed 'recipients' from `DiscussionComposer` (no longer confusion on what it does)
- Created new `PrivateDiscussionComposer`
- Added some help/info text to `AddRecipientModal`
- Added a cancel button to `AddRecipientModal`, removed the 'X' to make it clearer on how to get out
- Fix issue where admin cannot send PD from user controls dropdown #78 

image

image

image

image

image

image

### CODE REVIEW

**Comment by luceos** [comment]
That's awesome Ian; looks like the use of Byobu on giffgaff is guaranteeing it to become mature much faster than hoped for 👍

**Comment by imorland** [comment]
Thanks @luceos 🙂 The tough calls are going to be if we want some of the more controversial changes in FoF. I guess that’s where feature switches and toggles come into play 🧐

**Comment by imorland** [comment]
Thanks @Ralkage for taking the time to look at this 🙂

I will take a look at these points tomorrow, but I do know that the startuser issue on blueprint is resolved in #89

**Comment by hrvoje-hr** [comment]
@imorland tags options in this Byobu UX PR are still present. Do you have plans to make it like on GiffGaff and remove this option?

**Comment by imorland** [comment]
Yes, I plan to introduce the requirement of tags as an extension settings option

**Comment by hrvoje-hr** [comment]
One thing: When admin reenables tags extension, tags box in private discussion composer is missing and it's possible to post PD without tags.

That's great by me, but I suppose that wasn't your intention. Let me know if you need me to open a new issue.

**Pull request merged**
