### PR TITLE
Fixes/improvements for byobu beta 7

### PR DESCRIPTION
**Pull request by davwheat**
**I've got a bunch of local changes to push that improve a11y and the first bullet, but it broke everything and it's 3am.**

**Changes proposed in this pull request:**
- Fix recipients modal styling issue
- Adds frontend typings for better development
- Hide admin page translation relating to Tags if tags is not installed
- Extract Prettier config to `.prettierrc`
- Bump Webpack CLI
- Conversions to Typescript and more modern code
- Use core `[deleted]` text instead of custom translation
- Use `oninput` instead of `onkeyup` to support copy-pasting
- Clean up Less
- Merge recipient label borders when next to one another (no more 2px borders!)

**Reviewers should focus on:**

**Screenshot**

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related [Flarum core extension PR's](https://github.com/flarum/core/pulls): (Omit this section if irrelevant)

### CODE REVIEW

**Comment by imorland** [comment]
I think it's entirely possible that you forgot in your sleep deprived state to commit the file(s) that address `Fix recipients modal styling issue` to this PR @davwheat

**Comment by davwheat** [comment]
Oh god I did... 😅

**Comment by davwheat** [comment]
I'm going to get back on this tonight when I get home from college -- sorry about the wait! 🙈

**Comment by imorland** [comment]
Cool, thanks @davwheat :)

Ping me if you need anything, I'll be around tonight

**Comment by imorland** [comment]
Also, this will become `1.0.0-beta.7` ;)

**Comment by davwheat** [comment]
Ok, I think it's ready for review now! Everything works (unless you find it doesn't of course :see_no_evil:)

**Comment by Ornanovitch** [comment]
Hey! Will https://github.com/FriendsOfFlarum/byobu/commit/2b5a11a3a8175d9abc081e30cc07080b4b8bd459 be added to `1.0.0-beta.7` also, as it resolves a little but important [issue](https://discuss.flarum.org/d/4762-friendsofflarum-by-bu-well-integrated-advanced-private-discussions/1003)?

**Comment by davwheat** [comment]
@Ornanovitch Cherry-picked that commit and made it a PR: #154

**Comment by Ornanovitch** [comment]
You rock thanks :sunglasses:

**Review by imorland — APPROVED** [review]

**Pull request merged**
