### PR TITLE
Private Messaging UX Improvements

### PR DESCRIPTION
**Pull request by andrewdyer**
- Removed private discussion creation flow from normal discussions.
- Added private discussion creation flow to members profile page.
- Made it so private discussions do not require a tag.
- Created a private discussions as a nav item on session dropdown.
- Added notification options on new private discussions.

### CODE REVIEW

**Comment by luceos** [comment]
This is huge. I understand the reasoning behind this, but I'll need to think about whether we want this for the general public.

Ping @jordanjay29 @datitisev @clarkwinkelmann

**Comment by clarkwinkelmann** [comment]
Can we maybe get some screenshots for reviewers who won't clone the project ?

Given Shahiem's PM extension will be coming with a more traditional UI, maybe it's not really needed for Byobu to try to do the same.

**Comment by rob006** [comment]
> Given Shahiem's PM extension will be coming with a more traditional UI, maybe it's not really needed for Byobu to try to do the same.

The difference is that Byouby extension is already available and it is free, while Shahiem's PM is going to be premium extension and it is in "coming soon" state since over 6 months.

**Comment by andrewdyer** [comment]
Our changes have been deployed and running in production. They can be previewed here https://community.giffgaff.com/

**Comment by luceos** [comment]
I am going to close this because new changes are continuously coming in. Feel free to open a new PR (or re-open this one) whenever you feel ready for a review.

Thank you, I think we would like to adopt (most of) these changes.

**Comment by datitisev** [comment]
Also, screenshots would also be nice if you do send another PR - not everyone has perms for byobu in your forum to observe the UI changes :P. It would also help if the changes are shown without your forum-specific CSS, as that does modify quite a bit of the UI.

**Comment by hrvojeHR** [comment]
@andrewdyer @luceos  I've tested this PR on freshly installed Flarum beta11. Unfortunately, it doesn't work from the user side.

UI is sorted as well as is on Giffgaff and everything works until the modal window. There are problems with adding recipients and "Post Discussion" doesn't work.

- Using "Send 'user' private message" opens a modal with the sender as the only Recipient (on Giffgaff other user is correctly set)
- Using "Send 'user' private message" where is sender picket instead the user, it's impossible to add manually that particular user. However, it's possible to add anyone else
- Post Discussion doesn't work. Nothing happens.

**Comment by hrvoje-hr** [comment]
@imorland @harrygiffgaff @andrewdyer just a reminder for a post above. I know that you guys work primarily for GiffGaff, but I would like to know did you manage to get this to work on plain Flarum? 

As I mentioned above, this PR merged with master doesn't work on Flarum beta 11.

**Comment by imorland** [comment]
@hrvoje-hr No, the commits here unfortunately do have a few issues, which have now been resolved and are now working on the [giffgaff community](https://community.giffgaff.com). We have not had the time to organise a PR back here yet.

It is something that we hope to do in the near future, but at present can't be any more specific than that.

**Comment by askvortsov1** [comment]
Just wanted to hop on the bandwagon, say that this looks awesome, and I would really like to see it included in Byobu.

**Comment by askvortsov1** [comment]
Possible ideas for additions (probably has been considered but still):
- A Mail icon in the top navbar, maybe with unread PM notifications?
- Adding a Private Messages view alongside "All Discussions" "Tags", and "Following"

**Comment by imorland** [comment]
Just a small update, @hrvoje-hr & others:

We (giffgaff) will start working within the next week or two on a replacement PR for these features, plus fixes and improvements.

**Comment by hrvoje-hr** [comment]
Great, thx guys!

**Pull request closed without merging**
