### PR TITLE
Notifications for new PD created

### PR DESCRIPTION
**Pull request by imorland**
Partially addresses #75

### CODE REVIEW

**Comment by datitisev** [comment]
It all looks good to me. I did notice that the forum name isn't included in the email subject. As of right now, Flarum hardcodes `[<forum name>] ` before the email subjects, so we probably want to add it to. 

Not sure if it should be in the translation or not, core doesn't do it that way, but it should be included.

**Comment by imorland** [comment]
@datitisev yea, I did consider the forum name in the title, then figured that the email <from> field is almost always going to be the forum name, so didn't want to duplicate. 

What are your thoughts?

**Comment by datitisev** [comment]
@imorland well, we probably want to keep it consistent with the rest of the Flarum emails

**Comment by luceos** [comment]
Let's push that into a translation key, that way anyone can override it with linguist or a custom lang pack.

**Comment by imorland** [comment]
@datitisev @luceos 

Added in translation file :)

**Comment by imorland** [comment]
Tiredness related git mistakes whilst squashing, please see replacement PR #81

**Pull request closed without merging**
