### PR TITLE
Replace t is undefined error with proper message if tag slug is invalid

### LINKED ISSUE #104: Submitting private discussions ends up in JS error
When submitting a private discussion it ends up in a JS error:
image

The error:
```
Model.js:303 Uncaught TypeError: Cannot read property 'data' of undefined
    at t.getIdentifier (Model.js:303)
    at Array.map (<anonymous>)
    at e.save (Model.js:142)
    at e.s.onsubmit (PrivateDiscussionComposer.js:30)
    at e.<anonymous> (removeTags.js:16)
    at e.t.<computed> (extend.js:61)
    at e.<anonymous> (removeTags.js:16)
    at e.t.<computed> (extend.js:61)
    at e.<anonymous> (removeTags.js:16)
    at e.t.<computed> (extend.js:61)
    at e.n.onsubmit (TextEditor.js:182)
    at HTMLButtonElement.H.t.<computed> (mithril.js:1286)
t.getIdentifier @ Model.js:303
e.save @ Model.js:142
s.onsubmit @ PrivateDiscussionComposer.js:30
(anonymous) @ removeTags.js:16
t.<computed> @ extend.js:61
(anonymous) @ removeTags.js:16
t.<computed> @ extend.js:61
(anonymous) @ removeTags.js:16
t.<computed> @ extend.js:61
n.onsubmit @ TextEditor.js:182
H.t.<computed> @ mithril.js:1286
```

Flarum info:
```
Flarum core 0.1.0-beta.12
PHP version: 7.4.3
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, memcache, msgpack, mysqli, PDO_Firebird, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache
+---------------------------------+----------------+--------+
| Flarum Extensions               |                |        |
+---------------------------------+----------------+--------+
| ID                              | Version        | Commit |
+---------------------------------+----------------+--------+
| flarum-approval                 | v0.1.0-beta.12 |        |
| flarum-bbcode                   | v0.1.0-beta.12 |        |
| flarum-emoji                    | v0.1.0-beta.12 |        |
| flarum-lang-english             | v0.1.0-beta.12 |        |
| flarum-flags                    | v0.1.0-beta.12 |        |
| flarum-likes                    | v0.1.0-beta.12 |        |
| flarum-lock                     | v0.1.0-beta.12 |        |
| flarum-markdown                 | v0.1.0-beta.12 |        |
| flarum-mentions                 | v0.1.0-beta.12 |        |
| flarum-statistics               | v0.1.0-beta.12 |        |
| flarum-sticky                   | v0.1.0-beta.12 |        |
| flarum-subscriptions            | v0.1.0-beta.12 |        |
| flarum-suspend                  | v0.1.0-beta.12 |        |
| flarum-tags                     | v0.1.0-beta.12 |        |
| noriods-auto-more               | 0.3.0          |        |
| flagrow-sitemap                 | 0.2.0          |        |
| fof-drafts                      | 0.1.4          |        |
| fof-follow-tags                 | 0.3.4          |        |
| fof-forum-statistics-widget     | 0.1.1          |        |
| fof-links                       | 0.2.1          |        |
| fof-moderator-notes             | 0.1.1          |        |
| fof-nightmode                   | 0.4.0          |        |
| fof-pwned-passwords             | 0.3.0          |        |
| fof-share-social                | 0.1.2          |        |
| fof-socialprofile               | 0.1.1          |        |
| fof-spamblock                   | 0.2.1          |        |
| fof-upload                      | 0.8.3          |        |
| v17development-seo              | 1.1            |        |
| the-turk-quiet-edits            | 0.1.1          |        |
| the-turk-password-strength      | 0.1.2          |        |
| clarkwinkelmann-lock-likes      | 1.0.0          |        |
| fof-recaptcha                   | 0.1.2          |        |
| fof-terms                       | 0.4.1          |        |
| zerosonesfun-hashtags           | 1.4.2          |        |
| fof-pages                       | 0.3.1          |        |
| fof-formatting                  | 0.1.4          |        |
| fof-disposable-emails           | 0.1.0          |        |
| wiwatsrt-best-answer            | v0.2.4         |        |
| michaelbelgium-discussion-views | v3.1.0         |        |
| clarkwinkelmann-circle-groups   | 0.2.1          |        |
| fof-username-request            | 0.2.0          |        |
| reflar-twofactor                | 0.1.3          |        |
| fof-byobu                       | 0.4.4          |        |
| zerosonesfun-announce           | 1.3            |        |
| fof-reactions                   | 0.2.1          |        |
| flagrow-analytics               | 0.8.0          |        |
| fof-pretty-mail                 | 0.1.6          |        |
| fof-user-directory              | 0.3.4          |        |
| reflar-level-ranks              | 1.2.1          |        |
| fof-filter                      | 0.1.0-beta.2   |        |
| the-turk-diff                   | 0.1.0-beta.7   |        |
| zerosonesfun-spoiler            | 1.2            |        |
| zerosonesfun-tooltip            | 1.1            |        |
| fof-prevent-necrobumping        | 0.2.0          |        |
| fof-stopforumspam               | 0.2.1          |        |
| fof-default-user-preferences    | 0.2.0          |        |
+---------------------------------+----------------+--------+
Debug mode: off
```

I know the error is not really helpful, but please just let me know if you need any further details. Thanks for any help in advance!

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
Fixes #104

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
Another option here would be instead of not setting any tag, I could set a random tag (first one from the store), which will then trigger the existing "Invalid tag for private discussions" error from the backend, instead of the "minimum 1 tag required" error from the Tags extension.

**Comment by clarkwinkelmann** [comment]
@imorland should I tag a new release or did you want to do it ?

**Comment by imorland** [comment]
@clarkwinkelmann can you hold on for a moment please? I'm just investigating a report of notifications not firing is 0.4.4

If it needs a fix, it would make sense to wrap it all together for a new tag - if that's ok with you?

**Comment by clarkwinkelmann** [comment]
@imorland works for me. I'll let you take care of it.

I just wanted to make sure it's not being forgotten after I saw the merge notification.

**Pull request merged**
